name: SABRI DRAGON BUILDER

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: ğŸ› ï¸ Setup Heavy Tools
        run: |
          sudo apt update
          sudo apt install -y git zip unzip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-pip
          pip3 install --user --upgrade buildozer cython==0.29.33 virtualenv

      - name: ğŸ—ï¸ Build APK with Sabri Power
        run: |
          buildozer android debug
        env:
          ACCEPT_SDK_LICENSE: "yes"

      - name: ğŸ“¦ Upload Sabri APK
        uses: actions/upload-artifact@v4
        with:
          name: SABRI-DRAGON-V4-APK
          path: bin/*.apk
